# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/matlon',
                'doc_host': 'https://mtln.github.io',
                'git_url': 'https://github.com/mtln/matlon',
                'lib_path': 'matlon'},
  'syms': {'matlon.core': {'matlon.core.foo': ('core.html#foo', 'matlon/core.py')}}}
