# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/matlon',
                'doc_host': 'https://mtln.github.io',
                'git_url': 'https://github.com/mtln/matlon',
                'lib_path': 'matlon'},
  'syms': { 'matlon.model': { 'matlon.model.Project': ('model.html#project', 'matlon/model.py'),
                              'matlon.model.Project.__eq__': ('model.html#project.__eq__', 'matlon/model.py'),
                              'matlon.model.Project.short_title': ('model.html#project.short_title', 'matlon/model.py'),
                              'matlon.model.load_projects': ('model.html#load_projects', 'matlon/model.py'),
                              'matlon.model.project_to_markdown': ('model.html#project_to_markdown', 'matlon/model.py'),
                              'matlon.model.projects_to_dot': ('model.html#projects_to_dot', 'matlon/model.py')}}}
